### ISSUE TITLE
Add sound volume info

### ISSUE THREAD

**Issue by kainonergon** [kainonergon/simplepanel#3]

**Comment by Chrysostomus** [comment]
Do you want pulseaudio or alsa? I was quite satisfied with how this was implemented in limepanel. It only updates when interacted with:

https://github.com/Chrysostomus/lemonpanel/blob/master/bin/volume
https://github.com/Chrysostomus/lemonpanel/blob/master/bin/volume_status.sh

**Comment by kainonergon** [comment]
Perhaph I will borrow your code then

**Comment by kainonergon** [comment]
Done with ALSA in https://github.com/kainonergon/simplepanel/commit/a1adfe4b8b103bbe03336ad4079079841cd13cd4
